from __future__ import unicode_literals

# Create your models here.

from django.db import models

"""Hobby is a template, Once customer subscribes to it, Hobby Service will be created"""

hobby_gender_choices = (
        ('F', 'Female'),
        ('M', 'Male'),
        ('B', 'Both'),
    )


class HobbyManager(models.Manager):

    def create(self, **validated_data):
        """
        Creates and saves hobby
        """

        Hobby = self.model(
            name = validated_data.get('name', None),
            short_desc = validated_data.get('short_desc', None),
            text = validated_data.get('text', None),
            status = validated_data.get('status', None),
            suggested_age_lower = validated_data.get('suggested_age_lower', None),
            suggested_age_upper = validated_data.get('suggested_age_upper', None),
            available_to_gender = validated_data.get('available_to_gender', None),
        )

        Hobby.save(using=self._db)
        return Hobby


class Hobby(models.Model):
    #default id field generated by django, serves as uniquely identifying field for hobby
    hobby_status_choices = (
        ('UC', 'UnderConstruction'),
        ('UR', 'UnderReview'),
        ('SU', 'Submitted'),
        ('PU', 'Published'),
    )
    objects = HobbyManager()
    name = models.CharField(max_length=50,
                            help_text='name of the hobby, ex: Cooking, Photography, DocumentaryMaking',)
    short_desc = models.CharField(max_length=500, help_text='brief description of the hobby',)
    text = models.TextField(help_text='full text of the hobby with benefits applicable',)
    status = models.CharField(max_length=2, choices=hobby_status_choices,
                              help_text='different statuses available for hobby')
    suggested_age_lower = models.SmallIntegerField(help_text='identifies the subscribers lowest eligible age limit',)
    suggested_age_upper = models.SmallIntegerField(help_text='identifies the subscribers upper eligible age limit',)
    available_to_gender = models.CharField(max_length=1,  choices=hobby_gender_choices,
                                           help_text='identifies the eligible genders who can subscribe to this hobby',)


class HobbyServiceManager(models.Manager):

    def create(self, **validated_data):
        """
        Creates and saves Hobby service.
        """

        HobbyService = self.model(
            hobby_id = validated_data.get('hobby_id', None),
            user_id = validated_data.get('user_id', None),
            nick_name = validated_data.get('nick_name', None),
            status = validated_data.get('status', None),
            end_date = validated_data.get('end_date', None),
        )

        HobbyService.save(using=self._db)
        return HobbyService

class HobbyService(models.Model):
    #default id field generated by django serves as uniquely identifying field for hobby service
    hobby_service_status_choices = (
       ('E', 'Effective'), ('D', 'Dormant'), ('C', 'Completed')
    )
    objects = HobbyServiceManager()
    hobby_id = models.ForeignKey('Hobby', on_delete=models.CASCADE,
                                 help_text='identifies the hobby template to which customer subscribed to',)
    user_id = models.ForeignKey('users.HUser', on_delete=models.CASCADE,
                                      help_text='identifies the customer signed up for the hobby',)
    nick_name = models.CharField(max_length=50,
                                 help_text='customer given name for the hobby, like "my photography hobby"')
    status = models.CharField(max_length=1, choices=hobby_service_status_choices,
                              help_text='status of the hobby status')
    end_date = models.DateField(blank=True, help_text='')
    creation_timestamp = models.DateTimeField(auto_now_add=True, auto_now=False, editable=False,
                                              help_text='date and time when customer first subscribed to this Hobby',)

    last_update_timestamp = models.DateTimeField(auto_now_add=False, auto_now=True,
                                                 help_text='date and time when customer last updated this Hobby',)


class HobbyReviewManager(models.Manager):

    def create(self, **validated_data):
        """
        Creates and saves hobby review.
        """

        HobbyReview = self.model(
            hobby_id = validated_data.get('hobby_id', None),
            user_id = validated_data.get('user_id', None),
            rating = validated_data.get('rating', None),
            comments = validated_data.get('comments', None),
        )

        HobbyReview.save(using=self._db)
        return HobbyReview



class HobbyReview(models.Model):
    #default id field generated by django serves as uniquely identifying field for hobby service
    rating_choices = (
        (1, '*'),
        (2, '**'),
        (3, '***'),
        (4, '****'),
        (5, '*****')
    )
    objects = HobbyReviewManager()
    hobby_id = models.ForeignKey('Hobby', on_delete=models.CASCADE,
                                 help_text='uniquely identifies the hobby')
    user_id = models.ForeignKey('users.HUser', on_delete=models.CASCADE,
                                      help_text='identifies the customer who gave the rating and wrote a review',)
    rating = models.SmallIntegerField(choices=rating_choices, help_text='identifies the customers rating',)
    comments = models.TextField(blank=True, help_text='customers review comments',)
