# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_auto_20160303_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinereview',
            name='comments',
            field=models.TextField(blank=True, help_text='users review comments', null=True),
        ),
        migrations.AlterField(
            model_name='routinereview',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], help_text='identifies the users rating'),
        ),
        migrations.AlterField(
            model_name='routinereview',
            name='user_id',
            field=models.ForeignKey(help_text='identifies the user who gave the rating and worote a review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
