# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_auto_20160309_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 9, 20, 57, 26, 348606, tzinfo=utc), help_text='date and time customer first subscribed to this component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine',
            name='publish_timestamp',
            field=models.DateTimeField(help_text='date and time customer first subscribed to this component', null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='available_to_gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('B', 'Both')], help_text='the eligible genders who can subscribe to this component', max_length=1),
        ),
        migrations.AlterField(
            model_name='routine',
            name='name',
            field=models.CharField(help_text='Name of the modeled component', max_length=50),
        ),
        migrations.AlterField(
            model_name='routine',
            name='short_desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='routine',
            name='status',
            field=models.CharField(choices=[('UC', 'UnderConstruction'), ('UR', 'UnderReview'), ('SU', 'Submitted'), ('PU', 'Published')], help_text='different statuses available for program', max_length=2),
        ),
        migrations.AlterField(
            model_name='routine',
            name='suggested_age_lower',
            field=models.SmallIntegerField(help_text='identifies the subscribers lowest eligible age limit'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='suggested_age_upper',
            field=models.SmallIntegerField(help_text='identifies the subscribers upper eligible age limit'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='text',
            field=models.TextField(help_text='full text of the component with risks and benefits applicable'),
        ),
    ]
