# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 21:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 9, 21, 57, 31, 915544, tzinfo=utc), help_text='date and time customer first subscribed to this component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='publish_timestamp',
            field=models.DateTimeField(help_text='date and time customer first subscribed to this component', null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='available_to_gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('B', 'Both')], help_text='the eligible genders who can subscribe to this component', max_length=1),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(help_text='Name of the modeled component', max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='short_desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('UC', 'UnderConstruction'), ('UR', 'UnderReview'), ('SU', 'Submitted'), ('PU', 'Published')], help_text='different statuses available for program', max_length=2),
        ),
        migrations.AlterField(
            model_name='habit',
            name='text',
            field=models.TextField(help_text='full text of the component with risks and benefits applicable'),
        ),
        migrations.AlterField(
            model_name='habitreview',
            name='comments',
            field=models.TextField(blank=True, help_text='users review comments', null=True),
        ),
        migrations.AlterField(
            model_name='habitreview',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], help_text='identifies the users rating'),
        ),
        migrations.AlterField(
            model_name='habitreview',
            name='user_id',
            field=models.ForeignKey(help_text='identifies the user who gave the rating and worote a review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habitservice',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time customer first subscribed to this component'),
        ),
        migrations.AlterField(
            model_name='habitservice',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitservice',
            name='last_update_timestamp',
            field=models.DateTimeField(auto_now=True, help_text='date and time customer last updated this component'),
        ),
        migrations.AlterField(
            model_name='habitservice',
            name='nick_name',
            field=models.CharField(help_text='customer given name for the component, like "my diabetes type2 program"', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='habitservice',
            name='status',
            field=models.CharField(choices=[('E', 'Effective'), ('D', 'Dormant'), ('C', 'Completed')], help_text='status of the program status', max_length=1),
        ),
        migrations.AlterField(
            model_name='habitservice',
            name='user_id',
            field=models.ForeignKey(help_text='identifies the customer signed up for the program', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='habitreview',
            unique_together=set([('habit_id', 'user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='habitservice',
            unique_together=set([('habit_id', 'user_id')]),
        ),
    ]
