# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 00:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20160310_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='picture',
            field=models.ImageField(default='pictures/HHLife2.png', max_length=254, upload_to='pictures/'),
        ),
    ]
