# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 10:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20160311_0017'),
    ]

    operations = [

    ]
