# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='health_condition_id',
            field=models.ForeignKey(default=1, help_text='each program is associated with a health condition', on_delete=django.db.models.deletion.CASCADE, to='programs.HealthCondition'),
            preserve_default=False,
        ),
    ]
