# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_program_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='picture',
            field=models.ImageField(default='pictures/HHLife2.png', max_length=254, upload_to='pictures/'),
        ),
    ]
