# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbys', '0002_auto_20160218_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hobbyreview',
            unique_together=set([('hobby_id', 'user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='hobbyservice',
            unique_together=set([('hobby_id', 'user_id')]),
        ),
    ]
