# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengereview',
            unique_together=set([('challenge_id', 'user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='challengeservice',
            unique_together=set([('challenge_id', 'user_id')]),
        ),
    ]
